### ISSUE TITLE
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

### ISSUE THREAD

**Issue by jerryan9999** [ecthros/uncaptcha#11]
Your computer or network may be sending automated queries. To protect our users, we can't process your request right now. For more details visit our help page

**Comment by jerryan9999** [comment]
@ecthros

**Comment by ecthros** [comment]
Hello,

Thanks for coming to visit this code. Unfortunately, this code is just intended to be a proof of concept, and Google has since drastically changed its selenium detection algorithm. As a result, it is expected behavior to receive the error you did. Please read the readme as it might clear up any more questions you have!
